imageRepository: huevarios
imageTag: latest

services:
  frontend:
    image: frontend
    port: 8080
    servicePort: 80
    env:
      PRODUCT_CATALOG_SERVICE_ADDR: "productcatalogservice:3550"
      CURRENCY_SERVICE_ADDR: "currencyservice:7000"
      CART_SERVICE_ADDR: "cartservice:7070"
      RECOMMENDATION_SERVICE_ADDR: "recommendationservice:8080"
      SHIPPING_SERVICE_ADDR: "shippingservice:50051"
      CHECKOUT_SERVICE_ADDR: "checkoutservice:5050"
      AD_SERVICE_ADDR: "adservice:9555"
      ENABLE_PROFILER: "0"
      SHOPPING_ASSISTANT_SERVICE_ADDR: "shoppingassistantservice:80"

  adservice:
    image: adservice
    port: 9555

  cartservice:
    image: cartservice
    port: 7070
    env:
      REDIS_ADDR: "redis-cart:6379"

  checkoutservice:
    image: checkoutservice
    port: 5050
    env:
      PRODUCT_CATALOG_SERVICE_ADDR: "productcatalogservice:3550"
      SHIPPING_SERVICE_ADDR: "shippingservice:50051"
      PAYMENT_SERVICE_ADDR: "paymentservice:50051"
      EMAIL_SERVICE_ADDR: "emailservice:5000"
      CURRENCY_SERVICE_ADDR: "currencyservice:7000"
      CART_SERVICE_ADDR: "cartservice:7070"

  currencyservice:
    image: currencyservice
    port: 7000
    env:
      PORT: "7000"
      DISABLE_PROFILER: "1"

  emailservice:
    image: emailservice
    port: 5000

  paymentservice:
    image: paymentservice
    port: 50051
    env:
      PORT: "50051"
      DISABLE_PROFILER: "1"

  productcatalogservice:
    image: productcatalogservice
    port: 3550

  recommendationservice:
    image: recommendationservice
    port: 8080
    env:
      PRODUCT_CATALOG_SERVICE_ADDR: "productcatalogservice:3550"

  shippingservice:
    image: shippingservice
    port: 50051

redis:
  name: redis-cart
  image: redis:alpine
  port: 6379


